"""
app.py
------
AIgnition 3.0 -- Probabilistic Revenue Forecasting for E-commerce Marketing

Run locally:
    streamlit run app.py

This file is NOT part of the graded run.sh pipeline, it is the interactive layer for judges/demo purposes,
sitting on top of the same src/ modules that run.sh uses.
"""
import os
import sys
import glob
import tempfile

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))
from utils import ingest_all, validate_campaign_consistency, clean_for_modeling
from forecasting import (weekly_aggregate, fit_segment_model, simulate_forecast,
                          compute_fresh_baseline, forecast_budget_curve)
from insights import segment_causal_summary, portfolio_summary, zscore_anomalies

st.set_page_config(page_title="AIgnition | Probabilistic Revenue Forecasting", layout="wide", page_icon="📈")

# ---------------------------------------------------------------------------
# Sidebar -- data source & controls
# ---------------------------------------------------------------------------
st.sidebar.title("📈 AIgnition 3.0")
st.sidebar.caption("Probabilistic Revenue Forecasting for E-commerce Marketing")

data_mode = st.sidebar.radio("Data source", ["Use bundled sample data", "Upload my own CSVs"])

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

if data_mode == "Upload my own CSVs":
    uploaded = st.sidebar.file_uploader(
        "Upload Google / Meta / Microsoft Ads campaign CSVs",
        type="csv", accept_multiple_files=True,
        help="Filenames should mention google/meta/bing so they're auto-detected.")
    if uploaded:
        tmp_dir = tempfile.mkdtemp()
        for uf in uploaded:
            with open(os.path.join(tmp_dir, uf.name), "wb") as f:
                f.write(uf.getbuffer())
        DATA_DIR = tmp_dir
    else:
        st.sidebar.info("No files uploaded yet -- showing bundled sample data.")

horizon_days = st.sidebar.select_slider("Forecast horizon (days)", options=[30, 60, 90], value=30)
budget_mult = st.sidebar.slider("Future media budget scenario (× current spend)", 0.25, 3.0, 1.0, 0.05)

st.sidebar.divider()
st.sidebar.caption(
    "AI-assisted causal summaries in this prototype are generated by a fully "
    "offline, rule-based statistical reasoning layer (no external LLM API "
    "calls) -- see 'AI Integration Strategy' in the Technical Documentation."
)

# ---------------------------------------------------------------------------
# Cached pipeline
# ---------------------------------------------------------------------------
@st.cache_data(show_spinner=False)
def load_and_prepare(data_dir: str):
    raw = ingest_all(data_dir)
    report = validate_campaign_consistency(raw)
    clean = clean_for_modeling(raw)
    return raw, report, clean


@st.cache_data(show_spinner=False)
def build_segment_models(_clean: pd.DataFrame, level: str):
    """level: 'channel' | 'channel_type' | 'campaign'"""
    if level == "channel":
        weekly = weekly_aggregate(_clean, ["channel"])
        groups = weekly.groupby("channel")
    elif level == "channel_type":
        weekly = weekly_aggregate(_clean, ["channel", "campaign_type"])
        groups = weekly.groupby(["channel", "campaign_type"])
    else:
        weekly = weekly_aggregate(_clean, ["channel", "campaign_type", "campaign_id", "campaign_name"])
        groups = weekly.groupby(["channel", "campaign_type", "campaign_id", "campaign_name"])

    results = {}
    for key, g in groups:
        model = fit_segment_model(g)
        results[key] = {"weekly": g, "model": model}
    return results


st.title("Probabilistic Revenue Forecasting for E-commerce Marketing")
st.caption("AIgnition 3.0 · NetElixir Hackathon Submission · Working Prototype")

try:
    raw, report, clean = load_and_prepare(DATA_DIR)
except Exception as e:
    st.error(f"Could not ingest data from `{DATA_DIR}`: {e}")
    st.stop()

tab_ingest, tab_forecast, tab_budget, tab_insights = st.tabs(
    ["1 · Data Ingestion & Validation", "2 · Forecasts", "3 · Budget Simulation", "4 · AI-Assisted Insights"]
)

# ---------------------------------------------------------------------------
# TAB 1 -- Ingestion & validation
# ---------------------------------------------------------------------------
with tab_ingest:
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Rows ingested", f"{report['n_rows']:,}")
    c2.metric("Campaigns", f"{report['n_campaigns']:,}")
    c3.metric("Channels", len(report["channels"]))
    c4.metric("Date range", f"{report['date_range'][0]} → {report['date_range'][1]}")

    st.subheader("Channels detected")
    st.write(", ".join(report["channels"]))

    st.subheader("Campaign-consistency validation report")
    if report["issues"]:
        for issue in report["issues"]:
            icon = {"warning": "⚠️", "info": "ℹ️"}.get(issue["severity"], "•")
            st.markdown(f"{icon} **{issue['check'].replace('_', ' ').title()}** "
                        f"— {issue['n_affected']:,} affected. {issue['detail']}")
    else:
        st.success("No consistency issues detected.")

    st.subheader("Raw ingested sample")
    st.dataframe(raw.head(200), use_container_width=True, height=280)

# ---------------------------------------------------------------------------
# TAB 2 -- Forecasts (channel / campaign-type / campaign)
# ---------------------------------------------------------------------------
with tab_forecast:
    level_label = st.radio("Forecast grain", ["Channel", "Campaign type", "Campaign"], horizontal=True)
    level_key = {"Channel": "channel", "Campaign type": "channel_type", "Campaign": "campaign"}[level_label]
    seg_models = build_segment_models(clean, level_key)

    def _display_name(key):
        if level_key == "channel":
            return key
        if level_key == "channel_type":
            return f"{key[0]} · {key[1]}"
        return f"{key[0]} · {key[1]} · {key[3]}"

    options = sorted(seg_models.keys(), key=_display_name)
    chosen = st.selectbox("Segment", options, format_func=_display_name)

    seg = seg_models[chosen]
    weekly, model = seg["weekly"], seg["model"]
    fresh_baseline = compute_fresh_baseline(weekly)
    future_daily_budget = fresh_baseline["base_weekly_spend"] / 7.0 * budget_mult

    res = simulate_forecast(model, horizon_days, future_daily_budget, fresh_baseline=fresh_baseline)

    m1, m2, m3, m4 = st.columns(4)
    m1.metric(f"Revenue (P50), {horizon_days}d", f"₹{res['revenue_p50']:,.0f}",
              help=f"P10 ₹{res['revenue_p10']:,.0f}  ·  P90 ₹{res['revenue_p90']:,.0f}")
    m2.metric("Blended ROAS (P50)", f"{res['roas_p50']:.2f}x",
              help=f"P10 {res['roas_p10']:.2f}x · P90 {res['roas_p90']:.2f}x")
    m3.metric("Scenario spend", f"₹{res['spend_scenario_total']:,.0f}")
    m4.metric("Spend-response elasticity", f"{res['elasticity_used']:.2f}",
              help="1.0 = revenue scales linearly with spend; <1 = diminishing returns.")

    # Historical + forecast band chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=weekly["week"], y=weekly["revenue"], mode="lines+markers",
                              name="Historical weekly revenue", line=dict(color="#2563eb")))
    n_weeks_fwd = max(1, round(horizon_days / 7))
    future_weeks = pd.date_range(weekly["week"].max() + pd.Timedelta(days=7), periods=n_weeks_fwd, freq="7D")
    p50_per_week = res["revenue_p50"] / n_weeks_fwd
    p10_per_week = res["revenue_p10"] / n_weeks_fwd
    p90_per_week = res["revenue_p90"] / n_weeks_fwd
    fig.add_trace(go.Scatter(x=future_weeks, y=[p90_per_week] * n_weeks_fwd, mode="lines",
                              line=dict(width=0), showlegend=False))
    fig.add_trace(go.Scatter(x=future_weeks, y=[p10_per_week] * n_weeks_fwd, mode="lines",
                              fill="tonexty", fillcolor="rgba(37,99,235,0.15)", line=dict(width=0),
                              name="P10–P90 range"))
    fig.add_trace(go.Scatter(x=future_weeks, y=[p50_per_week] * n_weeks_fwd, mode="lines+markers",
                              name="Forecast (P50, weekly avg)", line=dict(color="#f97316", dash="dash")))
    fig.update_layout(height=380, margin=dict(l=10, r=10, t=30, b=10),
                       yaxis_title="Weekly revenue (₹)", legend=dict(orientation="h", y=1.1))
    st.plotly_chart(fig, use_container_width=True)

    st.caption(f"Trailing average ROAS: {model.get('avg_roas', 0):.2f}x · "
               f"Weekly trend: {model.get('trend_weekly_pct', 0)*100:+.1f}% · "
               f"History used: {model.get('n_weeks', 0)} week(s)"
               + (" · ⚠️ limited history" if model.get("low_data_flag") else ""))

# ---------------------------------------------------------------------------
# TAB 3 -- Budget simulation
# ---------------------------------------------------------------------------
with tab_budget:
    st.write("Explore how revenue and ROAS respond to different future daily-budget scenarios "
             "for the segment selected in the Forecasts tab, using its fitted spend-response curve.")
    curve = forecast_budget_curve(model, horizon_days, fresh_baseline=fresh_baseline)
    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(x=curve["daily_budget"], y=curve["revenue_p50"], mode="lines+markers",
                               name="Revenue (P50)", line=dict(color="#2563eb")))
    fig2.add_trace(go.Scatter(x=curve["daily_budget"], y=curve["revenue_p10"], mode="lines",
                               line=dict(color="#93c5fd", dash="dot"), name="Revenue (P10)"))
    fig2.add_trace(go.Scatter(x=curve["daily_budget"], y=curve["revenue_p90"], mode="lines",
                               line=dict(color="#93c5fd", dash="dot"), name="Revenue (P90)"))
    fig2.update_layout(height=360, margin=dict(l=10, r=10, t=30, b=10),
                        xaxis_title="Future daily budget (₹)", yaxis_title=f"Revenue over {horizon_days}d (₹)")
    st.plotly_chart(fig2, use_container_width=True)

    fig3 = px.line(curve, x="daily_budget", y="roas_p50", markers=True,
                    labels={"daily_budget": "Future daily budget (₹)", "roas_p50": "ROAS (P50)"})
    fig3.update_layout(height=280, margin=dict(l=10, r=10, t=20, b=10))
    st.plotly_chart(fig3, use_container_width=True)

    st.dataframe(curve.style.format({
        "daily_budget": "₹{:.0f}", "revenue_p10": "₹{:.0f}", "revenue_p50": "₹{:.0f}",
        "revenue_p90": "₹{:.0f}", "roas_p50": "{:.2f}x",
    }), use_container_width=True)

# ---------------------------------------------------------------------------
# TAB 4 -- AI-assisted insights
# ---------------------------------------------------------------------------
with tab_insights:
    st.subheader("Segment causal summary")
    st.info(segment_causal_summary(_display_name(chosen), weekly, model, res))

    st.subheader("Anomaly detection (z-score vs 8-week rolling mean)")
    anomalies = zscore_anomalies(weekly)
    flagged = anomalies[anomalies["is_anomaly"]]
    if len(flagged):
        st.dataframe(flagged[["week", "revenue", "roll_mean", "z"]].style.format(
            {"revenue": "₹{:.0f}", "roll_mean": "₹{:.0f}", "z": "{:.2f}"}), use_container_width=True)
    else:
        st.success("No statistically significant anomalies detected in this segment's history.")

    st.divider()
    st.subheader("Portfolio-level executive summary")
    all_channel_models = build_segment_models(clean, "channel")
    portfolio_results = []
    for key, s in all_channel_models.items():
        fb = compute_fresh_baseline(s["weekly"])
        r = simulate_forecast(s["model"], horizon_days, fb["base_weekly_spend"] / 7.0 * budget_mult, fresh_baseline=fb)
        portfolio_results.append({"segment": key, "model": s["model"], "forecast": r})
    st.write(portfolio_summary(portfolio_results))
